ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_done INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ALTER COLUMN onboarding_done SET DEFAULT 0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ALTER COLUMN email_verified SET DEFAULT 0;

